DROP TABLE IF EXISTS todo;
-- DROP TABLE IF EXISTS tasks;

CREATE TABLE todo(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT  NOT NULL,
	tasks TEXT NOT NULL
);

-- CREATE TABLE tasks(
-- 	id INTEGER PRIMARY KEY AUTOINCREMENT,
-- 	author_id INTEGER NOT NULL,
-- 	work TEXT UNIQUE NOT NULL,
-- 	FOREIGN KEY (author_id) REFERENCES user (id)
-- );